#!/bin/bash

###
### SIGPI
###
### pkg_evilcrowrf
###
###
### 20260113-0100
###
### Evil Crow RF V2 driver installer
###

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : Evil Crow RF V2"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&
    remove )
        cd "$SIGPI_SOURCE"/evilcrowrf/build
        sudo make uninstall
        cd "$SIGPI_SOURCE"
        rm -rf "$SIGPI_SOURCE"/evilcrowrf
        sed -i /evilcrowrf/d "$SIGPI_INSTALLED"
        ;;&
    purge )
        cd "$SIGPI_SOURCE"/evilcrowrf/build
        sudo make uninstall
        cd "$SIGPI_SOURCE"
        rm -rf "$SIGPI_SOURCE"/evilcrowrf
        sed -i /evilcrowrf/d "$SIGPI_INSTALLED"
        sudo rm -rf "$SIGPI_DESKTOP"/evilcrowrf.desktop
        sudo rm -rf "$DESKTOP_FILES"/evilcrowrf.desktop
        ;;&
    install|build|package )
        ## DEPENDENCIES
        sudo apt-get install -y \
            build-essential \
            cmake \
            git \
            libusb-1.0-0-dev \
            libusb-dev \
            pkg-config
        ;;&    
    install )
        ## PACKAGE
        cd "$SIGPI_SOURCE"
        git clone --recursive https://github.com/joelsernamoreno/evilcrowrf.git
        cd evilcrowrf
        mkdir -p build
        cd build
        cmake ..
        make -j4
        sudo make install
        sudo ldconfig
        cat "$SIGPI_PKGLIST" | grep "evilcrowrf" >> "$SIGPI_INSTALLED"

        ## DESKTOP
        # Add Icon
        # Add Desktop
        sudo cp "$SIGPI_HOME"/desktop/evilcrowrf.desktop "$DESKTOP_FILES"
        # Change Category
        # Add to Menu
        xdg-desktop-menu install --novendor --noupdate "$DESKTOP_DIRECTORY"/SIGpishell.directory "$DESKTOP_FILES"/evilcrowrf.desktop
        ;;&
    build )
        ## PACKAGE
        cd "$SIGPI_SOURCE"
        git clone --recursive https://github.com/joelsernamoreno/evilcrowrf.git
        cd evilcrowrf
        mkdir -p build
        cd build
        cmake ..
        make -j4
        sudo make install
        sudo ldconfig
        cat "$SIGPI_PKGLIST" | grep "evilcrowrf" >> "$SIGPI_INSTALLED"

        ## DESKTOP
        # Add Icon
        # Add Desktop
        sudo cp "$SIGPI_HOME"/desktop/evilcrowrf.desktop "$DESKTOP_FILES"
        # Change Category
        # Add to Menu
        xdg-desktop-menu install --novendor --noupdate "$DESKTOP_DIRECTORY"/SIGpishell.directory "$DESKTOP_FILES"/evilcrowrf.desktop
        ;;&
    package )       
        ## PACKAGE
        git clone --recursive https://github.com/joelsernamoreno/evilcrowrf.git
        cd evilcrowrf
        mkdir -p build
        cd build
        cmake ..
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb "$SIGPI_DEBS"

        ## DESKTOP
        # Add Icon
        # Add Desktop
        # Change Category
        # Add to Menu
        ;;&
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : Evil Crow RF V2 - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&
    * )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac
