#!/bin/bash

###
### SIGpi
###
### pkg_sigutils
###
###
### 20260113-2300
###
### Digital signal processing library written in C, designed for blind signal analysis and automatic demodulation
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

case "$1" in 
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : SigUtils"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove )
        cd $SIGPI_SOURCE/sigutils
        cd build
        sudo make uninstall
        sudo ldconfig
        sudo rm -rf $SIGPI_SOURCE/sigutils*
        sed -i /sigutils/d $SIGPI_INSTALLED
        ;;&

    purge )
        cd $SIGPI_SOURCE/sigutils
        cd build
        sudo make uninstall
        sudo ldconfig
        sudo rm -rf $SIGPI_SOURCE/sigutils*
        sed -i /sigutils/d $SIGPI_INSTALLED
        ;;&

    install|build )
        cd $SIGPI_SOURCE
        git clone https://github.com/BatchDrake/sigutils.git
        cd sigutils
        mkdir build && cd build
        cmake ..
        make -j4
        sudo make install
        sudo ldconfig
        cat $SIGPI_PKGLIST|grep "sigutils" >> $SIGPI_INSTALLED 
        ;;&

    package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  Package option not available"
        echo -e "${SIGPI_BANNER_RESET}"
	    ;;&

    remove|purge|install|build )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : SigUtils - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac
