#!/bin/bash

###
### SIGPI
###
### pkg_srsran-5g
###
###
### 20260113-2300
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

case "$1" in 
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : srsRAN-5g"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove )
        sudo dpkg -r srsran-5g
        sed -i /srsran-5g/d $SIGPI_INSTALLED
        ;;&

    purge )
        sudo dpkg -P srsran-5g
        sed -i /srsran-5g/d $SIGPI_INSTALLED
        ;;&

    install )
        ## DEPENDENCIES
        sudo apt-get install -y libmbedtls-dev libboost-program-options-dev
        sudo apt-get install -y libconfig++-dev libsctp-dev

        ## PACKAGE
        cd $SIGPI_PACKAGES        
        if [[ "$SIGPI_HWARCH" == "x86_64" ]]; then
	        sudo dpkg -i srsran-5g
            cat $SIGPI_PKGLIST|grep "srsran-5g" >> $SIGPI_INSTALLED
        fi

        if [[ "$SIGPI_HWARCH" == "aarch64" ]]; then
	        cd $SIGPI_PACKAGES
	        echo -e "Not available for ARM64"
        fi
	    ;;&

    build )
        ## DEPENDENCIES
        sudo apt-get install -y libmbedtls-dev libboost-program-options-dev
        sudo apt-get install -y libconfig++-dev libsctp-dev
        cd $SIGPI_SOURCE
        git clone https://github.com/srsran/srsRAN_Project
        cd srsRAN_Project
        mkdir build ; cd build
        cmake ../
        make -j4
        sudo make install
        ;;&
    
    package )
        ## DEPENDENCIES
        sudo apt-get install -y libmbedtls-dev libboost-program-options-dev
        sudo apt-get install -y libconfig++-dev libsctp-dev
        cd $SIGPI_SOURCE
        git clone https://github.com/srsran/srsRAN_Project
        cd srsRAN_Project
        mkdir build ; cd build
        cmake ../
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGPI_DEBS
	    ;;&

    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : srsRAN-5g - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac
