#!/bin/bash

###
### SIGpi
###
### pkg_suscan
###
###
### 20260113-2300
###
### Suscan is a realtime DSP processing library. It provides a set of useful abstractions to perform
### dynamic digital signal analysis and demodulation. Suscan offers features like:
###
###    Multicore-friendly signal processing, based on worker threads
###    Generic ASK, FSK, PSK and audio demodulators
###    An extensible codec interface
###    Configuration file API (XML)
###    Source API based on SoapySDR
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

case "$1" in 
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : suscan"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove )
        cd $SIGPI_SOURCE/suscan
        cd build
        sudo make uninstall
        sudo ldconfig
        sudo rm -rf $SIGPI_SOURCE/suscan*
        sed -i /suscan/d $SIGPI_INSTALLED
        ;;&

    purge )
        cd $SIGPI_SOURCE/suscan
        cd build
        sudo make uninstall
        sudo ldconfig
        sudo rm -rf $SIGPI_SOURCE/suscan*
        sed -i /suscan/d $SIGPI_INSTALLED
        ;;&

    install|build )
        ## DEPEDENCIES

        ## PACKAGE
        cd $SIGPI_SOURCE
        git clone https://github.com/BatchDrake/suscan.git
        cd suscan
        git submodule update --init --recursive
        mkdir build && cd build
        cmake ..
        make -j4
        sudo make install
        sudo ldconfig
        cat $SIGPI_PKGLIST|grep "suscan" >> $SIGPI_INSTALLED

        ## DESKTOP
	    # Add Icon
        # Add Desktop
        # Change Category
	    # Add to Menu
        ;;&

    package )
        ## DEPEDENCIES

        ## PACKAGE
        cd $SIGPI_SOURCE
        git clone https://github.com/BatchDrake/suscan.git
        cd suscan
        git submodule update --init --recursive
        mkdir build && cd build
        cmake ..
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGPI_DEBS
        
        ## DESKTOP
	    # Add Icon
        # Add Desktop
        # Change Category
	    # Add to Menu
        ;;&

    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : suscan - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac
