#!/bin/bash

###
### SIGpi
###
### pkg_sdrangel
###
### 20260130-2300
###
### SDRangel package management script (aarch64-focused)
###

#
# COMPILER OPTIMIZATION (OPTIONAL)
#
# For a 64-bit operating system on a Raspberry Pi 3:
#export CXXFLAGS='-O3 -mtune=cortex-a53'
#export CFLAGS='-O3 -mtune=cortex-a53'
#
# For a 64-bit operating system on a Raspberry Pi 4:
#export CXXFLAGS='-O3 -mtune=cortex-a72'
#export CFLAGS='-O3 -mtune=cortex-a72'
#
# For a 64-bit operating system on a Raspberry Pi 5:
#export CXXFLAGS='-O3 -mtune=cortex-a76'
#export CFLAGS='-O3 -mtune=cortex-a76'
#
# For other operating systems:
#export CXXFLAGS='-O3 -march=native -mtune=native'
#export CFLAGS='-O3 -march=native -mtune=native'
#


# FUNCTIONS

nproc_safe() {
    local n
    n="$(nproc 2>/dev/null || echo 1)"
    if [[ -z "$n" || "$n" -lt 1 ]]; then
        echo 1
    else
        echo "$n"
    fi
}

cpu_flags() {
    # Allow override via SIGPI_CFLAGS
    if [[ -n "${SIGPI_CFLAGS:-}" ]]; then
        echo "${SIGPI_CFLAGS}"
        return
    fi

    if [[ -r /proc/cpuinfo ]]; then
        if grep -qi "Raspberry Pi 5" /proc/cpuinfo; then
            echo "-mcpu=cortex-a76 -mtune=cortex-a76"
            return 0
        fi
        if grep -qi "Raspberry Pi 4" /proc/cpuinfo; then
            echo "-mcpu=cortex-a72 -mtune=cortex-a72"
            return 0
        fi
        if grep -qi "Raspberry Pi 3" /proc/cpuinfo; then
            echo "-mcpu=cortex-a53 -mtune=cortex-a53"
            return 0
        fi
    else
        echo "-O3 -march=native -mtune=native"
        return 0    
    fi
}  

deps_install() {
    sudo apt-get update -y
    sudo apt-get install -y \
        libfftw3-dev \
        libusb-1.0-0-dev \
        libusb-dev \
        libboost-all-dev \
        libasound2-dev \
        libgl1-mesa-dev \
        gettext \
        pulseaudio \
        libopencv-dev \
        libxml2-dev \
        bison \
        flex \
        ffmpeg \
        libavcodec-dev \
        libavformat-dev \
        opus-tools \
        libopus-dev \
        graphviz \
        qt5-qmake \
        qtscript5-dev \
        qtbase5-dev \
        qtchooser \
        qtmultimedia5-dev \
        qml-module-qtlocation \
        qml-module-qtpositioning \
        qml-module-qtquick-window2 \
        qml-module-qtquick-dialogs \
        qml-module-qtquick-controls \
        qml-module-qtquick-layouts \
        qttools5-dev \
        qttools5-dev-tools \
        qtdeclarative5-dev \
        qtpositioning5-dev \
        qtlocation5-dev \
        libgl1-mesa-glx \
        libqt5opengl5-dev \
        libqt5quick5 \
        libqt5charts5-dev \
        libqt5websockets5-dev \
        libqt5multimedia5-plugins \
        libqt5serialport5-dev \
        libqt5texttospeech5-dev \
        libqt5svg5-dev \
        libqt5positioning5 \
        libqt5positioning5-plugins \
        libqt5gamepad5-dev \
        gstreamer1.0-libav \
        checkinstall \
        cmake \
        build-essential
}


# MAIN

set -euo pipefail

if [[ ! "${1:-}" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : SDRangel"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove )
        cd "$SIGPI_DEBS"
        sudo dpkg -r sdrangel || true
        sed -i /sdrangel/d "$SIGPI_INSTALLED"
        ;;&

    purge )
        cd "$SIGPI_DEBS"
        sudo dpkg -P sdrangel || true
        sed -i /sdrangel/d "$SIGPI_INSTALLED"
        ;;&

    install|build|package )
        deps_install
        ;;&

    install )
        ## PACKAGE
	    cd $SIGPI_DEBS 
        
        if [[ "$SIGPI_HWARCH" == "x86_64" ]]; then
	        sudo dpkg -i sdrangel_current_amd64.deb
        fi
        
        if [[ "$SIGPI_HWARCH" == "aarch64" ]]; then
	        sudo dpkg -i sdrangel_current_arm64.deb
        fi
        
        cat $SIGPI_PKGLIST|grep "sdrangel," >> $SIGPI_INSTALLED 
        ;;&

    build|package )
        cd $SIGPI_SOURCE
        git clone https://github.com/f4exb/sdrangel.git
        cd sdrangel
        git reset --hard 1236b11   # v7.23.0
        mkdir -p build
        cd build
        CFLAGS="$(cpu_flags)" CXXFLAGS="$(cpu_flags)" cmake -Wno-dev ..
cmake -Wno-dev -DDEBUG_OUTPUT=ON -DRX_SAMPLE_24BIT=ON \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DMIRISDR_DIR=/usr/local/lib/libmirisdr \
-DAIRSPY_DIR=/usr/local/lib/libairspy \
-DAIRSPYHF_DIR=/usr/local/lib/libairspyhf \
-DBLADERF_DIR=/usr/local/lib/libbladeRF \
-DHACKRF_DIR=/usr/local/lib/libhackrf \
-DRTLSDR_DIR=/usr/local/lib/librtlsdr \
-DLIMESUITE_DIR=/usr/local/lib/LimeSuite \
-DIIO_DIR=/usr/local/lib/libiio \
-DPERSEUS_DIR=/usr/local/lib/libperseus \
-DXTRX_DIR=/usr/local/lib/xtrx-images \
-DSOAPYSDR_DIR=/usr/local/lib/SoapySDR \
-DUHD_DIR=/usr/local/lib/uhd \
-DAPT_DIR=/usr/local/lib/aptdec \
-DCM256CC_DIR=/usr/local/lib/cm256cc \
-DDSDCC_DIR=/usr/local/lib/dsdcc \
-DSERIALDV_DIR=/usr/local/lib/serialdv \
-DMBE_DIR=/usr/local/lib/mbelib \
-DCODEC2_DIR=/usr/local/lib/codec2 \
-DSGP4_DIR=/usr/local/lib/sgp4 \
-DLIBSIGMF_DIR=/usr/local/lib/libsigmf \
-DDAB_DIR=/usr/local/lib/libdab \
-DGGMORSE_DIR=/usr/local/lib/ggmorse \
-DINMARSATC_DIR=/usr/local/lib/inmarsatc \
-DCMAKE_INSTALL_PREFIX=/usr/local/lib/sdrangel ..
make -j $(nproc) install


        make -j"$(nproc_safe)"
        ;;&

    build )
        sudo make install
        sudo ldconfig
        cat "$SIGPI_PKGLIST" | grep "sdrangel," >> "$SIGPI_INSTALLED"
        ;;&

    package )
        sudo checkinstall --install=no
        sudo mv ./*.deb "$SIGPI_DEBS"
        ;;&

    install|build )
        ## DESKTOP
        sudo cp "$SIGPI_DESKTOP/sdrangel.desktop" "$DESKTOP_FILES"
        sudo cp "$SIGPI_SCRIPTS/run_sdrangel.sh" /usr/local/bin

        ### FFTW-WISDOM CHECK AND LINK
        mkdir -p "$HOME/.config/f4exb"
        mkdir -p "$HOME/.local/share/f4exb/SDRangel"
        if [[ ! -f "$SIGPI_ETC/fftw-wisdom" ]]; then
            fftwf-wisdom -v -n -o "$SIGPI_ETC/fftw-wisdom" 128 256 512 1024 2048 4096 8192 16384 32768
        fi
        
        cp "$SIGPI_ETC/fftw-wisdom" "$HOME/.local/share/f4exb/SDRangel/fftw-wisdom"
        cp "$SIGPI_ETC/fftw-wisdom" "$HOME/.config/f4exb/fftw-wisdom"
        ;;&

    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : SDRangel - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;

esac
