#!/bin/bash

###
### SIGPI
###
### pkg_docker
###
###
### 20260130-2300
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

case "$1" in 
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : Docker"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove )
        sudo apt-get remove docker
        sed -i /docker/d $SIGPI_INSTALLED
        ;;&

    purge )
        sudo apt-get remove --purge docker
        sed -i /docker/d $SIGPI_INSTALLED
        ;;&

    install )
        # DEPENDENCIES

        # INSTALL
        cd $SIGPI_SOURCE
        mkdir docker && cd docker
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo bash get-docker.sh
        # Set SUDO user to use docker
        sudo usermod -aG docker $(whoami)

        # Docker Compose
        sudo apt install python3-pip -y
        sudo pip3 install docker-compose
        docker-compose version
        cat $SIGPI_PKGLIST|grep "docker" >> $SIGPI_INSTALLED
        ;;&

    build )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  SIGpi build option not available"
        echo -e "${SIGPI_BANNER_RESET}"
	    ;;&

    package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  SIGpi package option not available"
        echo -e "${SIGPI_BANNER_RESET}"
	    ;;&

    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : Docker - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac