#!/bin/bash

###
### SIGpi_menubuilder
###
###  20240110-0100
###
###
###  Usage:  SIGpi_menubuilder [ACTION]
###
###       ACTION
###
###          SIGpi_menubuilder standard   First time setup for desktop
###          SIGpi_menubuilder server     First time setup for server
###


###
### INIT VARIABLES AND DIRECTORIES
###

# SIGpi Directory tree
SIGPI_ROOT=$HOME/SIG
SIGPI_SOURCE=$SIGPI_ROOT/source
SIGPI_HOME=$SIGPI_ROOT/SIGpi
SIGPI_ETC=$SIGPI_ROOT/etc
SIGPI_DEVICES=$SIGPI_HOME/devices
SIGPI_SCRIPTS=$SIGPI_HOME/scripts
SIGPI_PACKAGES=$SIGPI_HOME/packages
SIGPI_DEBS=$SIGPI_HOME/debs

# SIGpi Install Support files
SIGPI_INSTALLED=$SIGPI_ETC/INSTALLED_PKGS
SIGPI_INSTALDEV=$SIGPI_ETC/INSTALLED_DEVS
SIGPI_PKGLIST=$SIGPI_PACKAGES/PACKAGES
SIGPI_DEVLIST=$SIGPI_DEVICES/DEVICES
SIGPI_SCREEN_STANDARD=$SIGPI_SCRIPTS/screen_standard_setup
SIGPI_SCREEN_SERVER=$SIGPI_SCRIPTS/screen_server_setup
SIGPI_SCREEN_DESKTOP=$SIGPI_ROOT/config/screen_standard_setup
SIGPI_SCREEN_SERVER=$SIGPI_ROOT/config/screen_server_setup

SIGPI_BANNER_COLOR="\e[0;104m\e[K"   # blue
SIGPI_BANNER_RESET="\e[0m"

# Detect architecture (x86, x86_64, aarch64, ARMv8, ARMv7)
SIGPI_HWARCH=`lscpu|grep Architecture|awk '{print $2}'`
# Detect Operating system (Debian GNU/Linux 11 (bullseye) or Ubuntu 22.04.3 LTS)
SIGPI_OSNAME=`cat /etc/os-release|grep "PRETTY_NAME"|awk -F'"' '{print $2}'`
# Is Platform good for install- true or false - we start with false
SIGPI_CERTIFIED="false"

# Desktop Source directories
SIGPI_BACKGROUNDS=$SIGPI_HOME/backgrounds
SIGPI_ICONS=$SIGPI_HOME/icons
SIGPI_LOGO=$SIGPI_HOME/logo
SIGPI_DESKTOP=$SIGPI_HOME/desktop

# Desktop Destination Directories
DESKTOP_DIRECTORY=/usr/share/desktop-directories
DESKTOP_FILES=/usr/share/applications
DESKTOP_ICONS=/usr/share/icons
DESKTOP_XDG_MENU=/usr/share/extra-xdg-menus

# SIGpi Menu category
SIGPI_MENU_CATEGORY=SIGpi
HAMRADIO_MENU_CATEGORY=HamRadio

# If we reached this point our hardware and operating system are certified for SIGpi

###
### FUNCTIONS
###

calc_wt_size() {
  # NOTE: it's tempting to redirect stderr to /dev/null, so supress error 
  # output from tput. However in this case, tput detects neither stdout or 
  # stderr is a tty and so only gives default 80, 24 values
  WT_HEIGHT=26
  WT_WIDTH=$(tput cols)

  if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
    WT_WIDTH=60
  fi
  if [ "$WT_WIDTH" -gt 178 ]; then
    WT_WIDTH=80
  fi
  WT_MENU_HEIGHT=$(($WT_HEIGHT-7))
}

select_startscreen(){
    TERM=ansi whiptail --title "SIGpi Setup" --clear --textbox $SIGPI_SCREEN_DESKTOP 34 100 16
}

select_startsrvscreen(){
    TERM=ansi whiptail --title "SIGpi Server Setup" --clear --textbox $SIGPI_SCREEN_SERVER 34 100 16
}

select_devices() {
    FUN=$(whiptail --title "Devices Setup" --clear --checklist --separate-output \
        "Choose additional SDR devices " 20 80 12 \
        "bladerf" "bladeRF " OFF \
        "ettus" "Ettus Research USRP UHD " OFF \
        "limesuite" "LimeSDR " OFF \
        "plutosdr" "PlutoSDR " OFF \
        "sdrplay" "SDRPlay " OFF \
        3>&1 1>&2 2>&3)
    RET=$?
    if [ $RET -eq 1 ]; then
        $FUN = "NONE"
    fi

    IFS=' '     # space is set as delimiter
    read -ra ADDR <<< "$FUN"   # str is read into an array as tokens separated by IFS
    for i in "${ADDR[@]}"; do   # access each element of array
        echo $FUN >> $SIGPI_INSTALDEV
    done
}

select_server() {
    FUN=$(whiptail --title "Server Setup" --clear --checklist --separate-output \
        "Choose which server to run as a service" 20 120 12 \
        "openwebrx" "OpenWebRX " OFF \
        "rtltcpsrv" "RTL-TCP Server " OFF \
        "sdrangelsrv" "SDRangel Server " OFF \
        "soapysdrsrv" "SoapySDR Server " OFF \
        "dump1090" "Dump1090 Server " OFF \
        "radiosonde" "RadioSonde AutoRX " OFF \
		3>&1 1>&2 2>&3)
    RET=$?
    if [ $RET -eq 1 ]; then
        $FUN = "NONE"
    fi

    IFS=' '     # space is set as delimiter
    read -ra ADDR <<< "$FUN"   # str is read into an array as tokens separated by IFS
    for i in "${ADDR[@]}"; do   # access each element of array
        echo $FUN >> $SIGPI_INSTALLER
    done
}


###
###  MAIN
###

##
## Server Install 
##

if [ "$1" = "server" ]; then
    calc_wt_size
    select_startsrvscreen
    select_devices
    select_server
    TERM=ansi whiptail --title "SIGpi Server Setup" --clear --msgbox "Ready to continue" 12 120
    echo -e "##"
    echo -e "##   Done !!"
    echo -e "##"
fi

##
## Standard Install
##

if [ "$1" = "standard" ]; then
    calc_wt_size
    select_startscreen
    select_devices
    select_desktop

    TERM=ansi whiptail --title "SIGpi setup" --clear --msgbox "Ready to continuer" 12 120
    echo -e "##"
    echo -e "##   Done !!"
    echo -e "##"
fi
