#!/bin/bash

###
### SIGpi
###
###  20260117-2300
###
###
###  Usage:  SIGpi [ACTION] [TARGET|DEVICE]
###
###       ACTION
###  
###          install                install TARGET from current release
###          remove                 remove installed TARGET
###          purge                  remove installed TARGET and purge configs
###          build                  compile and install TARGET (option may not be available)
###          package                compile only and copy packaged to SIGpi/debs directory (option may not be available)
###          menu                   Gtk Menu for SIGpi package management
###          update                 check for TARGET updates
###          upgrade                upgrade TARGET to latest release
###
###          device
###                 install         install DEVICE
###                 remove          remove DEVICE
###                 purge           purge DEVICE
###                 build           compile and install DEVICE (option may not be available)
###                 package         compile only and copy package to SIGpi/debs directory (option may not be available)
###
###          setup
###                 standard        First time setup for desktop
###                 server          First time setup for server
###                 apps            Manage applications (install/remove)
###
###          list
###                 packages        List all packages included with SIGpi
###                 installed       List installed SIGpi packages
###                 library         List all packages included with SIGpi with installed ones marked with an *  
###
###          shell           provide SIGpi env variables around a TARGET
###
###       TARGET
###
###          A SIGpi package
###
###       DEVICE
###
###          A support SDR device
###


###
### INIT VARIABLES AND DIRECTORIES
###

# SIGpi Directory tree - the repo is cloned directly to $SIGPI_ROOT, so
# SIGPI_HOME (the repo checkout) and SIGPI_ROOT (the project root) are the
# same directory; source/ and etc/ are untracked runtime dirs inside it.
SIGPI_ROOT=$HOME/SIGpi
SIGPI_HOME=$SIGPI_ROOT
SIGPI_SOURCE=$SIGPI_ROOT/source
SIGPI_ETC=$SIGPI_ROOT/etc
SIGPI_DEVICES=$SIGPI_HOME/devices
SIGPI_SCRIPTS=$SIGPI_HOME/scripts
SIGPI_PACKAGES=$SIGPI_HOME/packages
SIGPI_DEBS=$SIGPI_HOME/debs
SIGPI_CONFIG=$SIGPI_HOME/config

# SIGpi Install Support files
SIGPI_INSTALLED=$SIGPI_ETC/INSTALLED_PKGS
SIGPI_PKGLIST=$SIGPI_PACKAGES/PACKAGES
SIGPI_INSTALLED_DEVICES=$SIGPI_ETC/INSTALLED_DEVICES
SIGPI_DEVLIST=$SIGPI_DEVICES/DEVICES
SIGPI_SCREEN_STANDARD=$SIGPI_SCRIPTS/screen_standard_setup
SIGPI_SCREEN_SERVER=$SIGPI_SCRIPTS/screen_server_setup
SIGPI_BANNER_COLOR="\e[0;104m\e[K"   # blue
SIGPI_BANNER_RESET="\e[0m"

# Desktop Source directories
SIGPI_BACKGROUNDS=$SIGPI_HOME/backgrounds
SIGPI_BACKGROUND_CHOICE=/usr/share/backgrounds/SIGpi_background_two.png
SIGPI_ICONS=$SIGPI_HOME/icons
SIGPI_LOGO=$SIGPI_HOME/logo
SIGPI_DESKTOP=$SIGPI_HOME/desktop

# Desktop Destination Directories
#DESKTOP_DIRECTORY=/usr/share/desktop-directories
DESKTOP_BACKGROUNDS=/usr/share/backgrounds
DESKTOP_FILES=/usr/share/applications
DESKTOP_ICONS=/usr/share/icons     #   .png .svg
#DESKTOP_XDG_MENU=/usr/share/extra-xdg-menus

# SIGpi Menu category
SIGPI_MENU_CATEGORY=SIGpi
HAMRADIO_MENU_CATEGORY=HamRadio

# Detect architecture (x86, x86_64, aarch64, ARMv8, ARMv7)
SIGPI_HWARCH=`lscpu|grep Architecture|awk '{print $2}'`
# Detect Operating system display name (Debian GNU/Linux 13 (trixie) or Ubuntu 24.04.4 LTS)
SIGPI_OSNAME=`cat /etc/os-release|grep "PRETTY_NAME"|awk -F'"' '{print $2}'`
# Detect Operating system codename (noble, trixie) - this is what we actually certify against
SIGPI_OSCODENAME=`. /etc/os-release; echo "$VERSION_CODENAME"`
# Is this box a Raspberry Pi (as opposed to generic amd64/arm64 Debian/Ubuntu hardware)
SIGPI_IS_RPI="false"
if grep -qi "Raspberry Pi" /proc/device-tree/model 2>/dev/null; then
    SIGPI_IS_RPI="true"
fi
# Is Platform good for install- true or false - we start with false
SIGPI_CERTIFIED="false"

# Debian-native packaging helper functions (replaces checkinstall)
source $SIGPI_SCRIPTS/SIGpi_pkgbuild


###
### FUNCTIONS
###

sigpi_update(){
    # Check for available updates to package
    local pkgname="$1"
    if [ -z "$pkgname" ]; then
        echo "Usage: SIGpi update <package>"
        return 1
    fi

    mkdir -p "$HOME/Downloads"
    wget -q https://raw.githubusercontent.com/joecupano/SIGpi/main/packages/PACKAGES -O "$HOME/Downloads/PACKAGES.latest"

    if grep -q "^$pkgname," "$HOME/Downloads/PACKAGES.latest"; then
        SIG_PKGSTAMP=$(grep "^$pkgname," "$SIGPI_PKGLIST" | cut -d, -f2)
        SIG_PKGNEW=$(grep "^$pkgname," "$HOME/Downloads/PACKAGES.latest" | cut -d, -f2)
        if [ "$SIG_PKGNEW" != "$SIG_PKGSTAMP" ]; then
            echo "Update $SIG_PKGNEW is available"
        else
            echo "No updates available"
        fi
    else
        echo "Unknown package: $pkgname"
    fi
}

sigpi_upgrade(){
    # Remove Package, update local clone, install updated package
    cd $SIGPI_HOME
    source $SIGPI_PACKAGES/$SPKGSCRIPT remove
    git pull
    source $SIGPI_PACKAGES/$SPKGSCRIPT install
}

###
###  MAIN
###

ACTION=$1
SPACKAGE=$2
SPKGSCRIPT="pkg_$2"
SCFGSCRIPT="cfg_$2"

if [ "$1" = "device" ]; then
    SPKGSCRIPT="pkg_$3"
fi

case "$1" in 
    setup )
        if [ "$2" = "apps" ]; then
            source $SIGPI_SCRIPTS/setup_apps
        elif [ "$2" = "standard" ] || [ "$2" = "server" ] || [ "$2" = "framework" ]; then
            source $SIGPI_SCRIPTS/SIGpi_setup $2
        fi
        ;;

    list )
        if [ "$2" = "installed" ]; then
            echo " "
            echo -e "${SIGPI_BANNER_COLOR} ##"
            echo -e "${SIGPI_BANNER_COLOR} ##  SIGpi list installed"
            echo -e "${SIGPI_BANNER_COLOR} ##"
            echo -e "${SIGPI_BANNER_RESET}"
            echo " "
            echo -e "INSTALLED\t PACKAGE\t VERSION\t DESCRIPTION"
            echo " "
            awk 'BEGIN {FS=","} {printf "%-15s %-15s %-15s\n", $1, $2, $3}' $SIGPI_INSTALLED|more
        fi

        if [ "$2" = "packages" ]; then
            echo " "
            echo -e "${SIGPI_BANNER_COLOR} ##"
            echo -e "${SIGPI_BANNER_COLOR} ##  SIGpi list packages"
            echo -e "${SIGPI_BANNER_COLOR} ##"
            echo -e "${SIGPI_BANNER_RESET}"
            echo " "
            echo -e "PACKAGE\t VERSION\t DESCRIPTION"
            echo " "
            awk 'BEGIN {FS=","} {printf "%-15s %-15s %-15s\n", $1, $2, $3}' $SIGPI_PKGLIST|more
        fi

        if [ "$2" = "library" ]; then
                file1=$SIGPI_PKGLIST
                file2=$SIGPI_INSTALLED
                echo " "
                echo -e "${SIGPI_BANNER_COLOR} ##"
                echo -e "${SIGPI_BANNER_COLOR} ##  SIGpi list library"
                echo -e "${SIGPI_BANNER_COLOR} ##"
                echo -e "${SIGPI_BANNER_RESET}"
                echo " "
                echo -e "\tINSTALLED\t PACKAGE\t VERSION\t DESCRIPTION"
                while IFS= read -r line_file1
                do
                        if grep -qF "$line_file1" "$file2"; then
                                echo -e "*\t $line_file1"|awk 'BEGIN {FS=","} {printf "%-15s %-15s %-15s %-15s\n", " ", $1, $2, $3}'
                        else
                                echo -e " \t $line_file1"|awk 'BEGIN {FS=","} {printf "%-15s %-15s %-15s %-15s\n", " ", $1, $2, $3}'
                        fi
                done < "$file1"
        fi
        ;;

    build )
        source $SIGPI_PACKAGES/$SPKGSCRIPT build
        #sudo dpkg -i $SIGPI_DEBS/$2
        ;;

    package )
        source $SIGPI_PACKAGES/$SPKGSCRIPT package
        ;;

    remove )
        source $SIGPI_PACKAGES/$SPKGSCRIPT remove
        ;;

    purge )
        source $SIGPI_PACKAGES/$SPKGSCRIPT purge
        ;;

    install )
        source $SIGPI_PACKAGES/$SPKGSCRIPT install
        ;;

    menu )
        "$SIGPI_SCRIPTS/SIGpi_pkg_menu.py"
        ;;

    config )
        source $SIGPI_PACKAGES/$SCFGSCRIPT $3
        ;;

    update )
        sigpi_update $2
        ;;

    upgrade)
        sigpi_upgrade $2
        ;;

    device )
        case "$2" in
            build )
                source $SIGPI_DEVICES/$SPKGSCRIPT build
                ;;
        
            package )
                source $SIGPI_DEVICES/$SPKGSCRIPT package
                ;;

            remove )
                source $SIGPI_DEVICES/$SPKGSCRIPT remove
                ;;

            purge )
                source $SIGPI_DEVICES/$SPKGSCRIPT purge
                ;;

            install )
                source $SIGPI_DEVICES/$SPKGSCRIPT install
                ;;
        esac
        ;;

    shell )
        source $2
        ;;

    * )
        cat <<EOF

       Usage:  SIGpi [ACTION] [TARGET|DEVICE]

       ACTION
  
          install                install TARGET from current release
          remove                 remove installed TARGET
          purge                  remove installed TARGET and purge configs
          build                  compile and install TARGET (option may not be available)
          package                compile only and copy packaged to SIGpi/debs directory (option may not be available)
          menu                   Gtk Menu for pSIGpi package management
          update                 check for TARGET updates
          upgrade                upgrade TARGET to latest release

          device
                 install         install DEVICE
                 remove          remove DEVICE
                 purge           purge DEVICE
                 build           compile and install DEVICE (option may not be available)
                 package         compile only and copy package to SIGpi/debs directory (option may not be available)

          setup
                 standard        First time setup for desktop
                 server          First time setup for server
                 apps            Manage applications (install/remove)

          list
                 packages        List all packages included with SIGpi
                 installed       List installed SIGpi packages
                 library         List all packages included with SIGpi with installed ones marked with an *  

          shell           provide SIGpi env variables around a TARGET

       TARGET

          A SIGpi package

       DEVICE

          A support SDR device

EOF
;;
esac

exit 0
