#!/bin/bash

###
### SIGPI
###
### device_rtlsdr-v4
###
###
### 20240110-0100
###

case "$1" in 
    remove )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Remove RTLSDR v4"
        echo -e "${SIGPI_BANNER_RESET}"

        cd $SIGPI_SOURCE/rtl-sdr-blog/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
	rm -rf $SIGPI_SOURCE/rtl-sdr-blog
        sed -i /rtlsdr-v4/d $SIGPI_CONFIG
	
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   RTLSDR v4 Removed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    purge )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Purge RTLSDR v4"
        echo -e "${SIGPI_BANNER_RESET}"

        cd $SIGPI_SOURCE/rtl-sdr-blog/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
	rm -rf $SIGPI_SOURCE/rtl-sdr-blog
        sed -i /rtlsdr-v4/d $SIGPI_INSTALLED

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   RTLSDR v4 Purged"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    install )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   Install RTLSDR v4"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"

        ## DEPENDENCIES
        sudo apt purge ^librtlsdr
        sudo rm -rvf /usr/lib/librtlsdr* /usr/include/rtl-sdr* /usr/local/lib/librtlsdr* /usr/local/include/rtl-sdr* /usr/local/include/rtl_* /usr/local/bin/rtl_* 
        sudo apt-get install libusb-1.0-0-dev
        
        ## PACKAGE
        cd $SIGPI_SOURCE
        git clone https://github.com/rtlsdrblog/rtl-sdr-blog
        cd rtl-sdr-blog
        mkdir build && cd build
        cmake ../ -DINSTALL_UDEV_RULES=ON
        make -j4
        sudo make install
        sudo cp ../rtl-sdr.rules /etc/udev/rules.d/
        sudo ldconfig
        echo 'blacklist dvb_usb_rtl28xxu' | sudo tee --append /etc/modprobe.d/blacklist-dvb_usb_rtl28xxu.conf
        cat $SIGPI_DEVLIST|grep "rtlsdr-v4" >> $SIGPI_INSTALDEV 

        
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   RTLSDR v4 Installed"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
     build )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   Build RTLSDR v4"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"

        ## DEPENDENCIES
        sudo apt purge ^librtlsdr
        sudo rm -rvf /usr/lib/librtlsdr* /usr/include/rtl-sdr* /usr/local/lib/librtlsdr* /usr/local/include/rtl-sdr* /usr/local/include/rtl_* /usr/local/bin/rtl_* 
        sudo apt-get install libusb-1.0-0-dev
        
        ## PACKAGE
        cd $SIGPI_SOURCE
        git clone https://github.com/rtlsdrblog/rtl-sdr-blog
        cd rtl-sdr-blog
        mkdir build && cd build
        cmake ../ -DINSTALL_UDEV_RULES=ON
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGPI_DEBS
        
        ## DESKTOP
	# Add Icon
        # Add Desktop
        # Change Category
	# Add to Menu

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   RTLSDR v4 Built. Debian package available in $SIGPI_DEBS"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    * )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac
