#!/bin/bash

###
### SIGPI
###
### device_rtlsdr
###
###
### 20240110-0100
###

case "$1" in 
    remove )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Remove RTLSDR"
        echo -e "${SIGPI_BANNER_RESET}"

        cd $SIGPI_SOURCE/rtl-sdr-blog/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
	rm -rf $SIGPI_SOURCE/rtl-sdr-blog
        sed -i /rtlsdr/d $SIGPI_INSTALLED
	
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   RTLSDR Removed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    purge )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Purge RTLSDR"
        echo -e "${SIGPI_BANNER_RESET}"

        cd $SIGPI_SOURCE/rtl-sdr-blog/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
	rm -rf $SIGPI_SOURCE/rtl-sdr-blog
        sed -i /rtlsdr/d $SIGPI_INSTALLED

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   RTLSDR Purged"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    install )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   Install RTLSDR"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"

        ## DEPENDENCIES
        sudo apt-get install -y libusb-1.0-0-dev
        sudo pip3 install pyrtlsdr

        ## PACKAGE
        cd $SIGPI_SOURCE
        git clone https://github.com/osmocom/rtl-sdr.git
        cd rtl-sdr
        mkdir build	&& cd build
        cmake ../ -DINSTALL_UDEV_RULES=ON -DDETACH_KERNEL_DRIVER=ON
        make
        sudo make install
        sudo cp ../rtl-sdr.rules /etc/udev/rules.d/
        sudo ldconfig
        cat $SIGPI_DEVLIST|grep "rtlsdr" >> $SIGPI_INSTALDEV 

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   RTLSDR Installed"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
     build )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   Build RTLSDR"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"

        ## DEPENDENCIES
        sudo apt purge ^librtlsdr
        sudo rm -rvf /usr/lib/librtlsdr* /usr/include/rtl-sdr* /usr/local/lib/librtlsdr* /usr/local/include/rtl-sdr* /usr/local/include/rtl_* /usr/local/bin/rtl_* 
        sudo apt-get install libusb-1.0-0-dev
        
        ## PACKAGE
        cd $SIGPI_SOURCE
        git clone https://github.com/rtlsdrblog/rtl-sdr-blog
        cd rtl-sdr-blog
        mkdir build && cd build
        cmake ../ -DINSTALL_UDEV_RULES=ON
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGPI_DEBS
        
        ## DESKTOP
	# Add Icon
        # Add Desktop
        # Change Category
	# Add to Menu

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   RTLSDR Built. Debian package available in $SIGPI_DEBS"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    * )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac
