#!/bin/bash

###
### SIGPI
###
### device_ettus
###
###
### 20230110-0100
###

case "$1" in 
    remove )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Remove Ettus UHD"
        echo -e "${SIGPI_BANNER_RESET}"
        
        cd $SIGPI_SOURCE/uhd/host/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
        rm -rf $SIGPI_SOURCE/uhd
        sed -i /ettus/d $SIGPI_INSTALLED

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Ettus UHD Removed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    purge )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Purge Ettus UHD"
        echo -e "${SIGPI_BANNER_RESET}"
       
        cd $SIGPI_SOURCE/uhd/host/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
        rm -rf $SIGPI_SOURCE/uhd
        sed -i /ettus/d $SIGPI_INSTALLED

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Ettus UHD Purged"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    install )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   Install Ettus UHD"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"

        ## DEPENDENCIES
        sudo apt-get install -y libboost-all-dev
        sudo apt-get install -y libusb-1.0-0-dev
        sudo apt-get install -y python3-mako

        ## PACKAGE
        cd $SIGPI_SOURCE
        git clone https://github.com/EttusResearch/uhd.git
        cd uhd
        git checkout UHD-4.5
        cd host
        mkdir build	&& cd build
        cmake .. -Wno-dev
        sudo make install
        sudo cp /usr/local/lib/uhd/utils/uhd-usrp.rules /etc/udev/rules.d/
        sudo ldconfig
        uhd_images_downloader
        cat $SIGPI_PKGLIST|grep "ettus" >> $SIGPI_INSTALLED 

        ## DESKTOP
        # Add Icon
        # Add Desktop
        # Change Directory
        # Add to Menu

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Ettus UHD Installed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    build )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   Build Ettus UHD"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"

        ## DEPENDENCIES
        sudo apt-get install -y libboost-all-dev
        sudo apt-get install -y libusb-1.0-0-dev
        sudo apt-get install -y python3-mako

        ## PACKAGE
        cd $SIGPI_SOURCE
        git clone https://github.com/EttusResearch/uhd.git
        cd uhd
        git checkout UHD-4.5
        cd host
        mkdir build	&& cd build
        cmake .. -Wno-dev
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGPI_DEBS

        ## DESKTOP
        # Add Icon
        # Add Desktop
        # Change Directory
        # Add to Menu
        
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Ettus UHD Built. Debian package available in $SIG_DEBS"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    * )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac
