#!/bin/bash

###
### SIGpi
###
### device_bladerf
###
###
### 20230110-0100
###

case "$1" in 
    remove )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Remove bladeRF"
        echo -e "${SIGPI_BANNER_RESET}"
        
	    cd $SIGPI_SOURCE/bladeRF/build/host
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
        rm -rf $SIGPI_SOURCE/bladeRF
        sed -i /bladerf/d $SIGPI_INSTALLED

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   bladeRF Removed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    purge )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Purge bladeRF"
        echo -e "${SIGPI_BANNER_RESET}"
               
	    cd $SIGPI_SOURCE/bladeRF/build/host
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
	    rm -rf $SIGPI_SOURCE/bladeRF
        sed -i /bladerf/d $SIGPI_INSTALLED

        rm -rf $HOME/.config/bladerf
        sudo rm -rf $SIGPI_DESKTOP/bladerf.desktop
        sudo rm -rf $DESKTOP_FILES/bladerf.desktop

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   bladeRF Purged"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    install )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   Install bladeRF"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"

        ## DEPENDENCIES
        sudo apt-get install python3-six python3-mako python3-lxml python3-lxml python3-numpy python3-numpy python3-pip git python3-pybind11 libsndfile1-dev

        ## PACKAGE 
        
        ### BladeRF
        cd $SIGPI_SOURCE
        git clone https://github.com/Nuand/bladeRF.git
        cd bladeRF
        mkdir build && cd build
        cmake .. -Wno-dev
        make
        sudo make install
        sudo ldconfig
        cat $SIGPI_DEVLIST|grep "bladerf" >> $SIGPI_INSTALDEV 
	
        ### SoapyBladeRF
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ###   - SoapyBladeRF "
        echo -e "${SIGPI_BANNER_RESET}"

        cd $SIGPI_SOURCE
        git clone https://github.com/pothosware/SoapyBladeRF.git
        cd SoapyBladeRF
        mkdir build && cd build
        cmake .. -Wno-dev
        make
        sudo make install
        sudo ldconfig

	    ## DESKTOP
	    # Add Icon
        # Add Desktop
        # Change Category
	    # Add to Menu

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   bladeRF Installed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    build )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   Build bladeRF"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"

        ## DEPENDENCIES
        sudo apt-get install python3-six python3-mako python3-lxml python3-lxml python3-numpy python3-numpy python3-pip git python3-pybind11 libsndfile1-dev
        ## PACKAGE 
        
        ### BladeRF
        cd $SIGPI_SOURCE
        git clone https://github.com/Nuand/bladeRF.git
        cd bladeRF
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo checkinstall --install=no

        ## DESKTOP
        # Add Icon
        # Add Desktop
        # Change Category
        # Add to Menu
	
        ### SoapyBladeRF
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ###   - SoapyBladeRF "
        echo -e "${SIGPI_BANNER_RESET}"

        cd $SIGPI_SOURCE
        git clone https://github.com/pothosware/SoapyBladeRF.git
        cd SoapyBladeRF
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo checkinstall --install=no
        sudo mv *.deb $SIGPI_DEBS

        ## DESKTOP
        # Add Icon
        # Add Desktop
        # Change Category
        # Add to Menu

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   bladeRF built. Debian package available in $SIG_DEBS"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    * )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac
