#!/bin/bash

###
### SIGPI
###
### device_ubertooth
###
###
### 20240110-0100
###

case "$1" in 
    remove )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   Remove Ubertooth Tools"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"

        cd $SIGPI_SOURCE/ubertooth/host/build
        sudo make uninstall
        cd $SIGPI_SOURCE
        rm -rf $SIGPI_SOURCE/ubertooth
        sed -i /ubertooth/d $SIGPI_INSTALLED
        
        ### Remove Menu icon
        sudo rm $SIGPI_DESKTOP_ICONS/ubertooth-tools.png
        ### Remove Desktop links
        sudo rm $SIGPI_DESKTOP_FILES/ubertooth-tools.desktop

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Ubertooth Tools Removed"
        ;;
    purge )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   Purge Ubertooth Tools"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"

        cd $SIGPI_SOURCE/ubertooth/host/build
        sudo make uninstall
        cd $SIGPI_SOURCE
        rm -rf $SIGPI_SOURCE/ubertooth
        sed -i /ubertooth/d $SIGPI_INSTALLED
        
        ### Remove Menu icon
        sudo rm $SIGPI_DESKTOP_ICONS/ubertooth-tools.png
        ### Remove Desktop links
        sudo rm $SIGPI_DESKTOP_FILES/ubertooth-tools.desktop
        
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Ubertooth Tools Purged"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    install )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   Install Ubertooth Tools"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"

        ## DEPENDENCIES
        sudo apt-get install -y libusb-1.0-0-dev 
        sudo apt-get install -y libbluetooth-dev 
        sudo apt-get install -y python3-qtpy 
        sudo apt-get install -y python3-distutils 
        sudo apt-get install -y python3-setuptools

        ## PACKAGE
        cd $SIGPI_SOURCE
        git clone https://github.com/greatscottgadgets/ubertooth.git
        cd ubertooth/host
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        cat $SIGPI_PKGLIST|grep "ubertooth" >> $SIGPI_INSTALLED 

        ## Desktop
        # Add icon
        # Add Desktop
        # Change Directory
        # Add to Menu
       
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Ubertooth Tools Installed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    build )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   SIGpi Build option not available"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    * )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac
