#!/bin/bash

###
### SIGPI
###
### device_libmirisdr
###
###
### 20230110-0100
###

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##"
echo -e "${SIGPI_BANNER_COLOR} ##   Install SDRplay RSPx Device"
echo -e "${SIGPI_BANNER_COLOR} ##"
echo -e "${SIGPI_BANNER_RESET}"

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ###   - Install RSPx Driver"
echo -e "${SIGPI_BANNER_RESET}"

# Remove Kernel Drivers
sudo modprobe -r msi2500 msi001
sudo cp $SIGPI_SCRIPTS/blacklist-msi.conf /etc/modprobe.d/blacklist-msi.conf

cd $SIGPI_SOURCE
git clone https://github.com/ericek111/libmirisdr-5
cd libmirisdr-5
mkdir build && cd build
cmake .. -Wno-dev
make -j4
sudo make install
sudo ldconfig
cat $SIGPI_DEVLIST|grep "libmirisdr" >> $SIGPI_INSTALDEV 

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ###   - RSPx Driver Installed"
echo -e "${SIGPI_BANNER_RESET}"

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ###   - Install SoapySDRplay Driver"
echo -e "${SIGPI_BANNER_RESET}"

cd $SIGPI_SOURCE
git clone https://github.com/ericek111/SoapyMiri
cd SoapyMiri
mkdir build && cd build
cmake .. -Wno-dev
make -j4
sudo make install
sudo ldconfig

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ###   - SoapySDRplay Driver Installed"
echo -e "${SIGPI_BANNER_RESET}"

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##   SDRplay RSPx Device Installed"
echo -e "${SIGPI_BANNER_RESET}"