#!/bin/bash

###
### SIGPI
###
### pkg_rtlsdr-v4
###
###
### 20260910-0100
###
### RTLSDR v4
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

# Fail fast on build errors: a failed compile/install step must not result
# in a broken .deb being staged or the package being marked installed.
# See sigpi_build_failed() in SIGpi_pkgbuild.
if [[ "$1" =~ ^(install|build|package)$ ]]; then
    set -Eeo pipefail
    trap 'sigpi_build_failed "${BASH_SOURCE[0]}" "$1" "$LINENO" "$?"' ERR
fi

case "$1" in 
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : rtlsdr-v4"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove|purge )
        cd $SIGPI_SOURCE/rtl-sdr-blog/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
	    rm -rf $SIGPI_SOURCE/rtl-sdr-blog
        sed -i /rtlsdr-v4/d $SIGPI_INSTALLED_DEVICES
        ;;&

    install|build|package )
        ## DEPENDENCIES
        sudo apt purge -y ^librtlsdr
        sudo rm -rvf /usr/lib/librtlsdr* /usr/include/rtl-sdr* /usr/local/lib/librtlsdr* /usr/local/include/rtl-sdr* /usr/local/include/rtl_* /usr/local/bin/rtl_* 
        sudo apt-get install -y libusb-1.0-0-dev
        ;;&

    install|build )
        ## PACKAGE
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch V1.4.0 https://github.com/rtlsdrblog/rtl-sdr-blog
        cd rtl-sdr-blog
        mkdir build && cd build
        cmake ../ -DINSTALL_UDEV_RULES=ON -DDETACH_KERNEL_DRIVER=ON -DENABLE_ZEROCOPY=ON
        make -j4
        sudo make install
        sudo ldconfig
        echo 'blacklist dvb_usb_rtl28xxu' | sudo tee --append /etc/modprobe.d/blacklist-rtl.conf
        cat $SIGPI_DEVLIST|grep "rtlsdr-v4" >> $SIGPI_INSTALLED_DEVICES

        cd $SIGPI_SOURCE
        git clone --depth 1 --branch soapy-rtlsdr-0.3.0 https://github.com/pothosware/SoapyRTLSDR.git
        cd SoapyRTLSDR
        mkdir build && cd build
        cmake .. -Wno-dev -DCMAKE_BUILD_TYPE=Release
        make -j4
        sudo make install
        sudo ldconfig
        ;;&

     package )
        ## PACKAGE
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch V1.4.0 https://github.com/rtlsdrblog/rtl-sdr-blog
        cd rtl-sdr-blog
        mkdir build && cd build
        cmake ../ -DINSTALL_UDEV_RULES=ON
        make -j4
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "rtlsdrv4" "1.4.0" "$(pwd)/pkgroot" "RTL-SDR Blog V4 dongle host tools and libraries"
        rm -rf pkgroot

        cd $SIGPI_SOURCE
        git clone --depth 1 --branch soapy-rtlsdr-0.3.0 https://github.com/pothosware/SoapyRTLSDR.git
        cd SoapyRTLSDR
        mkdir build && cd build
        cmake .. -Wno-dev -DCMAKE_BUILD_TYPE=Release
        make -j4
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "soapyrtlsdr" "0.3.0" "$(pwd)/pkgroot" "SoapySDR module for RTL-SDR devices"
        rm -rf pkgroot
        ;;&

    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : rtlsdr-v4 - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac
