#!/bin/bash

###
### SIGpi
###
### pkg_ettus
###
###
### 20260910-0100
###
### Ettus Research USRP Devices
###

case "$1" in 

    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : Ettus Research USRP Devices"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove )
        sudo dpkg -r uhd
        sed -i /uhd/d $SIGPI_INSTALLED_DEVICES
        ;;&

    purge )
        sudo dpkg -P uhd
        sed -i /uhd/d $SIGPI_INSTALLED_DEVICES
        sudo rm -rf $SIGPI_SOURCE/uhd*
        ;;&

    install|build|package )
        ## DEPENDENCIES
        sudo apt-get install -y libboost-all-dev
        sudo apt-get install -y libusb-1.0-0-dev
        sudo apt-get install -y python3-mako
        ;;&

    install )
        ## PACKAGE
        cd $SIGPI_PACKAGES
        if [[ "$SIGPI_HWARCH" == "x86_64" ]]; then
	        cd $SIGPI_DEBS
	        sudo dpkg -i uhd_current_amd64.deb
            cat $SIGPI_DEVLIST|grep "ettus" >> $SIGPI_INSTALLED_DEVICES
        fi

        if [[ "$SIGPI_HWARCH" == "aarch64" ]]; then
	        cd $SIGPI_DEBS
	        sudo dpkg -i uhd_current_arm64.deb
            cat $SIGPI_DEVLIST|grep "ettus" >> $SIGPI_INSTALLED_DEVICES
        fi
        ;;&

    build|package )
        ## PACKAGE
        # 20260910: UHD builds on aarch64 (Raspberry Pi 4/5, and Jetson/other
        # arm64 boards) via the same cmake-based host build used for x86_64 -
        # confirmed via UHD's linux-aarch64 conda-forge build and current
        # EttusResearch/uhd issue tracker (no open arm64 build blockers on
        # this release). No arch-specific cmake flags are required.
        cd $SIGPI_SOURCE
        git clone https://github.com/EttusResearch/uhd.git
        cd uhd
        git checkout v4.11.0.0
        cd host
        mkdir build	&& cd build
        cmake .. -Wno-dev
        make -j4
        ;;&

    build )
        sudo make install
        sudo cp /usr/local/lib/uhd/utils/uhd-usrp.rules /etc/udev/rules.d/
        sudo ldconfig
        sudo uhd_images_downloader
        cat $SIGPI_DEVLIST|grep "ettus" >> $SIGPI_INSTALLED_DEVICES
        ;;&

    package )
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "uhd" "4.11.0.0" "$(pwd)/pkgroot" "Ettus Research USRP Hardware Driver (UHD)"
        rm -rf pkgroot
        ;;&

    install|build|package|remove|purge )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : Ettus Research USRP Devices completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&
esac