#!/bin/bash

###
### SIGPI
###
### pkg_ubertooth
###
###
### 20260910-0100
###
### Ubertooth One is an open source 2.4 GHz wireless
### development platform suitable for Bluetooth experimentation
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown case "$1" in wn action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

# Fail fast on build errors: a failed compile/install step must not result
# in a broken .deb being staged or the package being marked installed.
# See sigpi_build_failed() in SIGpi_pkgbuild.
if [[ "$1" =~ ^(install|build|package)$ ]]; then
    set -Eeo pipefail
    trap 'sigpi_build_failed "${BASH_SOURCE[0]}" "$1" "$LINENO" "$?"' ERR
fi

case "$1" in 
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : ubertooth"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove )
        cd $SIGPI_SOURCE/libbtbb/build
        sudo make uninstall
        cd $SIGPI_SOURCE
        rm -rf $SIGPI_SOURCE/libbtbb
        sed -i /libbtbb/d $SIGPI_INSTALLED
        
        cd $SIGPI_SOURCE/ubertooth/host/build
        sudo make uninstall
        cd $SIGPI_SOURCE
        rm -rf $SIGPI_SOURCE/ubertooth
        sed -i /ubertooth/d $SIGPI_INSTALLED_DEVICES
        ;;&

    purge )
        cd $SIGPI_SOURCE/libbtbb/build
        sudo make uninstall
        cd $SIGPI_SOURCE
        rm -rf $SIGPI_SOURCE/libbtbb
        sed -i /libbtbb/d $SIGPI_INSTALLED
        
        cd $SIGPI_SOURCE/ubertooth/host/build
        sudo make uninstall
        cd $SIGPI_SOURCE
        rm -rf $SIGPI_SOURCE/ubertooth
        sed -i /ubertooth/d $SIGPI_INSTALLED_DEVICES

        ### Remove Menu icon
        sudo rm $SIGPI_DESKTOP_ICONS/ubertooth-tools.png
        ### Remove Desktop links
        sudo rm $SIGPI_DESKTOP_FILES/ubertooth-tools.desktop
        ;;&

    install|build )
        ## DEPENDENCIES
        sudo apt-get install -y libusb-1.0-0-dev 
        sudo apt-get install -y libbluetooth-dev 
        sudo apt-get install -y python3-qtpy 
        #sudo apt-get install -y python3-distutils 
        sudo apt-get install -y python3-setuptools

        ### LibBTBB Library
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch 2020-12-R1 https://github.com/greatscottgadgets/libbtbb.git
        cd libbtbb
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        sudo ldconfig
        cat $SIGPI_PKGLIST|grep "libbtbb" >> $SIGPI_INSTALLED

        ### Ubertooth
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch 2020-12-R1 https://github.com/greatscottgadgets/ubertooth.git
        cd ubertooth/host
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        cat $SIGPI_DEVLIST|grep "libbtbb" >> $SIGPI_INSTALLED_DEVICES
        ;;&

    package )
        ## DEPENDENCIES
        sudo apt-get install -y libusb-1.0-0-dev 
        sudo apt-get install -y libbluetooth-dev 
        sudo apt-get install -y python3-qtpy 
        #sudo apt-get install -y python3-distutils 
        sudo apt-get install -y python3-setuptools

        ### LibBTBB Library
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch 2020-12-R1 https://github.com/greatscottgadgets/libbtbb.git
        cd libbtbb
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "libbtbb" "2020-12-R1" "$(pwd)/pkgroot" "Bluetooth baseband decoding library used by Ubertooth"
        rm -rf pkgroot

        ### Ubertooth
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch 2020-12-R1 https://github.com/greatscottgadgets/ubertooth.git
        cd ubertooth/host
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "ubertooth" "2020-12-R1" "$(pwd)/pkgroot" "Ubertooth One host tools for Bluetooth experimentation"
        rm -rf pkgroot
	    ;;&

    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : ubertooth - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac