#!/bin/bash

###
### SIGPI
###
### pkg_sdrplay
###
### 20260124-2300
###
###
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

case "$1" in 
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : SDRplay"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove|purge )
	    cd $SIGPI_SOURCE/SDRplay/build/host
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
        rm -rf $SIGPI_SOURCE/SDRplay
        rm -rf $HOME/.config/SDRplay
        sudo rm -rf $SIGPI_DESKTOP/SDRplay.desktop
        sudo rm -rf $DESKTOP_FILES/SDRplay.desktop
        sed -i /sdrplay/d $SIGPI_INSTALLED_DEVICES
        ;;&

    install )
        cd $SIGPI_SOURCE
        unzip $SIGPI_DEBS/SDRplay_API_Linux-3.15.2.zip
        cd SDRplay_API_Linux-3.15.2
        sudo ./install_lib.sh
        sudo cp run_SDRplay.sh /usr/local/bin/run_SDRplay.sh
        sudo chmod 755 /usr/local/bin/run_SDRplay.sh
        cat $SIGPI_DEVLIST|grep "sdrplay" >> $SIGPI_INSTALLED_DEVICES
        ;;&

    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : SDRplay - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac