#!/bin/bash

###
### SIGPI
###
### pkg_hackrf
###
###
### 20260910-0100
###
### HackRF
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

case "$1" in 
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : HackRF"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove|purge )
       cd $SIGPI_SOURCE/hackrf/host/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
	    rm -rf $SIGPI_SOURCE/hackrf
        sed -i /hackrf/d $SIGPI_INSTALLED_DEVICES
	    ;;&

    install|build|package)
        ## DEPENDENCIES
        sudo apt-get install -y libusb-1.0-0-dev libfftw3-dev
        ;;&

    install|build )
        ## INSTALL
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch v2026.01.3 https://github.com/greatscottgadgets/hackrf.git
        cd hackrf/host
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        sudo ldconfig

        cd $SIGPI_SOURCE
        git clone --depth 1 --branch soapy-hackrf-0.3.4 https://github.com/pothosware/SoapyHackRF.git
        cd SoapyHackRF
        mkdir build && cd build
        cmake .. -Wno-dev -DCMAKE_BUILD_TYPE=Release
        make -j4
        sudo make install
        sudo ldconfig
        cat $SIGPI_DEVLIST|grep "hackrf" >> $SIGPI_INSTALLED_DEVICES
        ;;&

     package )
        ## INSTALL
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch v2026.01.3 https://github.com/greatscottgadgets/hackrf.git
        cd hackrf/host
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "hackrf" "2026.01.3" "$(pwd)/pkgroot" "HackRF host tools and libraries"
        rm -rf pkgroot

        cd $SIGPI_SOURCE
        git clone --depth 1 --branch soapy-hackrf-0.3.4 https://github.com/pothosware/SoapyHackRF.git
        cd SoapyHackRF
        mkdir build && cd build
        cmake .. -Wno-dev -DCMAKE_BUILD_TYPE=Release
        make -j4
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "soapyhackrf" "0.3.4" "$(pwd)/pkgroot" "SoapySDR module for HackRF devices"
        rm -rf pkgroot
        ;;&

    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : HackRF - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac