#!/bin/bash

###
### SIGpi
###
### pkg_fobos
###
###
### 20260117-2300
###
### RigExpert Fobos Device
###


if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

case "$1" in 
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   $1 : RigExpert Fobos"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove|purge )
        sudo dpkg -r libfobos
        sudo dpkg -r SoapyMiri
        sed -i /libfobos/d $SIGPI_INSTALLED_DEVICES
        ;;&

    install|build|package )
        ## Fobos driver
        cd $SIGPI_SOURCE
        git clone https://github.com/rigexpert/libfobos
        cd libfobos
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4

        ## SoapyFobosSDR Driver
        cd $SIGPI_SOURCE
        git clone https://github.com/rigexpert/SoapyFobosSDR
        cd SoapyFobosSDR
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        ;;&

    install|build )
        cd $SIGPI_SOURCE/libfobos/build
        sudo make install
        sudo ldconfig

        cd $SIGPI_SOURCE/SoapyFobosSDR/build    
        sudo make install
        sudo ldconfig
        cat $SIGPI_DEVLIST|grep "libfobos" >> $SIGPI_INSTALLED_DEVICES
        ;;&

    package)
        cd $SIGPI_SOURCE/libfobos/build
        sudo checkinstall --install=no
        sudo mv *.deb $SIGPI_DEBS

        cd $SIGPI_SOURCE/SoapyFobosSDR/build
        sudo checkinstall --install=no
        sudo mv *.deb $SIGPI_DEBS
        ;;&

    install|build|package|remove|purge )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   $1 : RigExpert Fobos completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    * )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac