#!/bin/bash

###
### SIGpi
###
### pkg_libmirisdr
###
###
### 20260910-0100
###
###
### open-source driver specifically designed for SDR devices
### built on the Mirics MSi001 + MSi2500 chipset. This includes:
### 
### - SDRplay RSP1
### - MSI-SDR / "M3" Receivers (RSP1 clones)
### - Mirics MSi2500 default dongles
### - Hauppauge WinTV 133559 LF: A specific TV tuner model 
### - AverMedia A859 Pure DVBT:
###

# Fail fast on build errors: a failed compile/install step must not result
# in a broken .deb being staged or the package being marked installed.
# See sigpi_build_failed() in SIGpi_pkgbuild.
if [[ "$1" =~ ^(install|build|package)$ ]]; then
    set -Eeo pipefail
    trap 'sigpi_build_failed "${BASH_SOURCE[0]}" "$1" "$LINENO" "$?"' ERR
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   $1 : libmirisdr"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove )
        cd $SIGPI_DEBS
        sudo dpkg -r libmirisdr
        sudo dpkg -r soapymirisdr
        sed -i /libmirisdr/d $SIGPI_INSTALLED_DEVICES
        sed -i /soapymirisdr/d $SIGPI_INSTALLED_DEVICES
        ;;&

    purge )
        cd $SIGPI_DEBS
        sudo dpkg -P libmirisdr
        sudo dpkg -P soapymirisdr
        sed -i /libmirisdr/d $SIGPI_INSTALLED_DEVICES
        sed -i /soapymirisdr/d $SIGPI_INSTALLED_DEVICES
        ;;&

    install )
        ## PACKAGE
        cd $SIGPI_PACKAGES        
        if [[ "$SIGPI_HWARCH" == "x86_64" ]]; then
	        cd $SIGPI_DEBS
	        sudo dpkg -i libmirisdr_current_amd64.deb
            sudo dpkg -i soapymirisdr_current_amd64.deb
        fi

        if [[ "$SIGPI_HWARCH" == "aarch64" ]]; then
	        cd $SIGPI_DEBS
            sudo dpkg -i libmirisdr_current_arm64.deb
            sudo dpkg -i soapymirisdr_current_arm64.deb
        fi
        cat $SIGPI_DEVLIST|grep "libmirisdr" >> $SIGPI_INSTALLED_DEVICES
        cat $SIGPI_DEVLIST|grep "soapymirisdr" >> $SIGPI_INSTALLED_DEVICES
        ;;&

    build|package )
        # Remove Kernel Drivers
        sudo modprobe -r msi2500 msi001
        sudo cp $SIGPI_CONFIG/blacklist-msi.conf /etc/modprobe.d/blacklist-msi.conf

        ## SDRplay driver
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch v1.1.2 https://github.com/ericek111/libmirisdr-5
        cd libmirisdr-5
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4

        ## SoapySDRplay Driver
        cd $SIGPI_SOURCE
        git clone https://github.com/ericek111/SoapyMiri
        cd SoapyMiri
        git checkout 1e0a125ebab4ab492266fc61cab52600c7dc675f # 20260910: no tagged releases upstream, pinned to HEAD as of this date
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        ;;&

    build )
        cd $SIGPI_SOURCE/libmirisdr-5/build
        sudo make install
        sudo ldconfig

        cd $SIGPI_SOURCE/SoapyMiri/build    
        sudo make install
        sudo ldconfig
        cat $SIGPI_DEVLIST|grep "libmirisdr" >> $SIGPI_INSTALLED_DEVICES
        ;;&
    
    package)
        cd $SIGPI_SOURCE/libmirisdr-5/build
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "libmirisdr" "1.1.2" "$(pwd)/pkgroot" "Open source driver for Mirics MSi001/MSi2500 based SDR devices"
        rm -rf pkgroot

        cd $SIGPI_SOURCE/SoapyMiri/build
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "soapymirisdr" "0+git20260910" "$(pwd)/pkgroot" "SoapySDR module for Mirics MSi001/MSi2500 based SDR devices"
        rm -rf pkgroot
        ;;&

    remove|purge|install|build|package)
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   $1 : Libmirisdr completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    * )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac