#!/bin/bash

###
### SIGpi
###
### pkg_ettus
###
###
### 20260117-2300
###
### Ettus Research USRP Devices
###

case "$1" in 

    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   $1 : Ettus Research USRP Devices"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove )
        cd $SIGPI_PACKAGES        
        if [[ "$SIGPI_HWARCH" == "x86_64" ]]; then
	        cd $SIGPI_DEBS
            sudo dpkg -r uhd
            sed -i /uhd/d $SIGPI_INSTALLED_DEVICES
        fi

        if [[ "$SIGPI_HWARCH" == "aarch64" ]]; then
	        cd $SIGPI_DEBS
            sudo dpkg -r uhd
            sed -i /uhd/d $SIGPI_INSTALLED_DEVICES
        fi
        ;;&

    purge )
        sudo dpkg -r uhd
        sed -i /uhd/d $SIGPI_INSTALLED_DEVICES
        sudo rm -rf $SIGPI_SOURCE/uhd*
        sed -i /uhd/d $SIGPI_INSTALLED_DEVICES
        ;;&

    install|build|package )
        ## DEPENDENCIES
        sudo apt-get install -y libboost-all-dev
        sudo apt-get install -y libusb-1.0-0-dev
        sudo apt-get install -y python3-mako
        ;;&

    install )
        ## PACKAGE
        cd $SIGPI_PACKAGES        
        if [[ "$SIGPI_HWARCH" == "x86_64" ]]; then
	        cd $SIGPI_DEBS
	        sudo dpkg -i uhd_current_amd64.deb
        fi

        if [[ "$SIGPI_HWARCH" == "aarch64" ]]; then
	        cd $SIGPI_DEBS
	        sudo dpkg -i uhd_current_arm64.deb
        fi
        cat $SIGPI_DEVLIST|grep "ettus" >> $SIGPI_INSTALLED_DEVICES
        ;;&
    
    build|package )
        ## PACKAGE
        cd $SIGPI_SOURCE
        git clone https://github.com/EttusResearch/uhd.git
        cd uhd
        git checkout v4.9.0.1
        cd host
        mkdir build	&& cd build
        cmake .. -Wno-dev
        make -j4
        ;;&

    install|build )
        sudo make install
        sudo cp /usr/local/lib/uhd/utils/uhd-usrp.rules /etc/udev/rules.d/
        sudo ldconfig
        sudo uhd_images_downloader
        cat $SIGPI_DEVLIST|grep "ettus" >> $SIGPI_INSTALLED_DEVICES
        ;;&

    package )
        sudo checkinstall --install=no
        sudo mv *.deb $SIGPI_DEBS
        ;;&

    install|build|package|remove|purge )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   $1 : Ettus Research USRP Devices completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    * )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac