#!/bin/bash

###
### SIGpi
###
### pkg_libmirisdr
###
###
### 20260110-2300
###
### SDRplay RSPx Device
###

case "$1" in 
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   $1 : libmirisdr"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove )
        cd $SIGPI_PACKAGES        
        if [[ "$SIGPI_HWARCH" == "x86_64" ]]; then
	        cd $SIGPI_DEBS
            sudo dpkg -r libmirisdr
            sudo dpkg -r soapymirisdr
            sed -i /libmirisdr/d $SIGPI_INSTALLED_DEVICES
            sed -i /soapymirisdr/d $SIGPI_INSTALLED_DEVICES
        fi

        if [[ "$SIGPI_HWARCH" == "aarch64" ]]; then
	        cd $SIGPI_DEBS
            sudo dpkg -r libmirisdr
            sudo dpkg -r soapymirisdr
            sed -i /libmirisdr/d $SIGPI_INSTALLED_DEVICES
            sed -i /soapymirisdr/d $SIGPI_INSTALLED_DEVICES
                fi
        ;;&

    purge )
        cd $SIGPI_PACKAGES        
        if [[ "$SIGPI_HWARCH" == "x86_64" ]]; then
	        cd $SIGPI_DEBS
            sudo dpkg -P libmirisdr
            sudo dpkg -P soapymirisdr
            sed -i /libmirisdr/d $SIGPI_INSTALLED_DEVICES
            sed -i /soapymirisdr/d $SIGPI_INSTALLED_DEVICES
        fi

        if [[ "$SIGPI_HWARCH" == "aarch64" ]]; then
	        cd $SIGPI_DEBS
            sudo dpkg -P libmirisdr
            sudo dpkg -P soapymirisdr
            sed -i /libmirisdr/d $SIGPI_INSTALLED_DEVICES
            sed -i /soapymirisdr/d $SIGPI_INSTALLED_DEVICES
                fi
        ;;&

    install )
        ## PACKAGE
        cd $SIGPI_PACKAGES        
        if [[ "$SIGPI_HWARCH" == "x86_64" ]]; then
	        cd $SIGPI_DEBS
	        sudo dpkg -i libmirisdr_current_amd64.deb
            sudo dpkg -i soapymirisdr_current_amd64.deb
        fi

        if [[ "$SIGPI_HWARCH" == "aarch64" ]]; then
	        cd $SIGPI_DEBS
            sudo dpkg -i libmirisdr_current_arm64.deb
            sudo dpkg -i soapymirisdr_current_arm64.deb
        fi
        cat $SIGPI_DEVLIST|grep "libmirisdr" >> $SIGPI_INSTALLED_DEVICES
        cat $SIGPI_DEVLIST|grep "soapymirisdr" >> $SIGPI_INSTALLED_DEVICES
        ;;&

    build|package )
        # Remove Kernel Drivers
        sudo modprobe -r msi2500 msi001
        sudo cp $SIGPI_CONFIG/blacklist-msi.conf /etc/modprobe.d/blacklist-msi.conf

        ## SDRplay driver
        cd $SIGPI_SOURCE
        git clone https://github.com/ericek111/libmirisdr-5
        cd libmirisdr-5
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4

        ## SoapySDRplay Driver
        cd $SIGPI_SOURCE
        git clone https://github.com/ericek111/SoapyMiri
        cd SoapyMiri
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        ;;&

    build )
        cd $SIGPI_SOURCE/libmirisdr-5/build
        sudo make install
        sudo ldconfig

        cd $SIGPI_SOURCE/SoapyMiri/build    
        sudo make install
        sudo ldconfig
        cat $SIGPI_DEVLIST|grep "libmirisdr" >> $SIGPI_INSTALLED_DEVICES
        ;;&
    
    package)
        cd $SIGPI_SOURCE/libmirisdr-5/build
        sudo checkinstall --install=no
        sudo mv *.deb $SIGPI_DEBS

        cd $SIGPI_SOURCE/SoapyMiri/build
        sudo checkinstall --install=no
        sudo mv *.deb $SIGPI_DEBS
        ;;&

    |remove|purge|install|build|package)
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   $1 : Libmirisdr completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    * )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac