#!/bin/bash

###
### SIGpi
###
### pkg_plutosdr
###
### 20260910-0100
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

case "$1" in 
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : PlutoSDR"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove|purge )
        sudo dpkg -r libiio
        sudo dpkg -r SoapyPlutoSDR
        sed -i /libiio/d $SIGPI_INSTALLED_DEVICES
        ;;&

    install|build|package )
        ## DEPENDENCIES
        sudo apt-get install -y libaio-dev libusb-1.0-0-dev 
        sudo apt-get install -y libserialport-dev libavahi-client-dev 
        sudo apt-get install -y libxml2-dev bison flex libcdk5-dev 
        sudo apt-get install -y python3 python3-pip python3-setuptools
        ;;&

    install|build )
        # INSTALL
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch v0.26 https://github.com/analogdevicesinc/libiio.git
        cd libiio
        #20260910: v0.26 is current upstream stable and builds fine against
        # this SoapyPlutoSDR release (confirmed via Arch Linux packaging of
        # soapyplutosdr 0.2.2 against libiio 0.26)
        mkdir build && cd build
        #20230830 Compile error not finding ZSTD though installed. So disable for now
        cmake .. -Wno-dev -WITH_ZSTD=OFF
        make -j4
        sudo make install
        sudo ldconfig

        # SoapyPlutoSDR
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch soapy-plutosdr-0.2.2 https://github.com/pothosware/SoapyPlutoSDR.git
        cd SoapyPlutoSDR
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        sudo ldconfig
        cat $SIGPI_DEVLIST|grep "plutosdr" >> $SIGPI_INSTALLED_DEVICES
        ;;&

    package )
        # INSTALL
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch v0.26 https://github.com/analogdevicesinc/libiio.git
        cd libiio
        #20260910: v0.26 is current upstream stable and builds fine against
        # this SoapyPlutoSDR release (confirmed via Arch Linux packaging of
        # soapyplutosdr 0.2.2 against libiio 0.26)
        mkdir build && cd build
        #20230830 Compile error not finding ZSTD though installed. So disable for now
        cmake .. -Wno-dev -WITH_ZSTD=OFF
        make -j4
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "libiio" "0.26" "$(pwd)/pkgroot" "Analog Devices Industrial I/O (IIO) library, used by PlutoSDR"
        rm -rf pkgroot

        cd $SIGPI_SOURCE
        git clone --depth 1 --branch soapy-plutosdr-0.2.2 https://github.com/pothosware/SoapyPlutoSDR.git
        cd SoapyPlutoSDR
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "soapyplutosdr" "0.2.2" "$(pwd)/pkgroot" "SoapySDR module for PlutoSDR devices"
        rm -rf pkgroot
        ;;&
    
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : PlutoSDR - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&
esac