#!/bin/bash

###
### SIGPI
###
### pkg_kerberos
###
###
### 20260910-0100
###
### Kerberos SDR
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

# Fail fast on build errors: a failed compile/install step must not result
# in a broken .deb being staged or the package being marked installed.
# See sigpi_build_failed() in SIGpi_pkgbuild.
if [[ "$1" =~ ^(install|build|package)$ ]]; then
    set -Eeo pipefail
    trap 'sigpi_build_failed "${BASH_SOURCE[0]}" "$1" "$LINENO" "$?"' ERR
fi

case "$1" in 
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : rtl-sdr-kerberos"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove )
        cd $SIGPI_SOURCE/rtl-sdr-kerberos/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
        rm -rf rtl-sdr-kerberos
        rm -rf SoapyRTLSDR
        sed -i /rtl-sdr-kerberos/d $SIGPI_INSTALLED_DEVICES
        ;;&

    purge )
        cd $SIGPI_SOURCE/rtl-sdr-kerberos/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
        rm -rf rtl-sdr-kerberos
        rm -rf SoapyRTLSDR
        sed -i /rtl-sdr-kerberos/d $SIGPI_INSTALLED_DEVICES
        ;;&

    install|build|package )
        ## DEPENDENCIES
        sudo apt-get install -y python3-pip python3-pyqt5 pyqt5-dev-tools gfortran libatlas3-base
        sudo apt-get install -y libatlas-base-dev python3-dev python3-setuptools 
        sudo apt-get install -y libffi-dev python3-tk pkg-config libfreetype6-dev php-cli
        sudo apt-get install -y libusb-1.0-0-dev
        pip3 install numpy
        pip3 install matplotlib
        pip3 install scipy
        pip3 install cairocffi
        pip3 install pyapril
        pip3 install pyargus
        pip3 install pyqtgraph
        pip3 install peakutils
        pip3 install bottle
        pip3 install paste
        ;;&

     install )
        ## PACKAGE
        cd $SIGPI_PACKAGES        
        if [[ "$SIGPI_HWARCH" == "x86_64" ]]; then
	        cd $SIGPI_DEBS
	        sudo dpkg -i rtl-sdr-kerberos_current_amd64.deb
        fi

        if [[ "$SIGPI_HWARCH" == "aarch64" ]]; then
	        cd $SIGPI_DEBS
	        sudo dpkg -i rtl-sdr-kerberos_current_arm64.deb
        fi
        cat $SIGPI_PKGLIST|grep "rtl-sdr-kerberos" >> $SIGPI_INSTALLED_DEVICES
        ;;&

    build )
        # PACKAGE
        cd $SIGPI_SOURCE
        git clone https://github.com/rtlsdrblog/rtl-sdr-kerberos
        cd rtl-sdr-kerberos
        git checkout 6b446a860e434d09d190c9e5c898646538710c6e # 20260910: no tagged releases upstream, pinned to HEAD as of this date
        mkdir build	&& cd build
        cmake .. -DINSTALL_UDEV_RULES=ON
        make -j4
        sudo make install
        cat $SIGPI_PKGLIST|grep "rtl-sdr-kerberos" >> $SIGPI_INSTALLED
        ;;&

    package )
        # PACKAGE
        cd $SIGPI_SOURCE
        git clone https://github.com/rtlsdrblog/rtl-sdr-kerberos
        cd rtl-sdr-kerberos
        git checkout 6b446a860e434d09d190c9e5c898646538710c6e # 20260910: no tagged releases upstream, pinned to HEAD as of this date
        mkdir build	&& cd build
        cmake .. -DINSTALL_UDEV_RULES=ON
        make -j4
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "rtl-sdr-kerberos" "0+git20260910" "$(pwd)/pkgroot" "KerberosSDR coherent RTL-SDR array tools"
        rm -rf pkgroot
        ;;&

    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : rtl-sdr-kerberos - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac