#!/bin/bash

###
### SIGpi
###
### pkg_bladerf
###
###
### 20260910-0100
###
### Nuand bladeRF and SoapyBladeRF
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

# Fail fast on build errors: a failed compile/install step must not result
# in a broken .deb being staged or the package being marked installed.
# See sigpi_build_failed() in SIGpi_pkgbuild.
if [[ "$1" =~ ^(install|build|package)$ ]]; then
    set -Eeo pipefail
    trap 'sigpi_build_failed "${BASH_SOURCE[0]}" "$1" "$LINENO" "$?"' ERR
fi

case "$1" in 
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : BladeRF"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove|purge )
        sudo apt-get remove -y bladerf bladerf-firmware bladerf-fpga
        
        cd $SIGPI_SOURCE/bladeRF/build/host
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
	    rm -rf $SIGPI_SOURCE/bladeRF
        sed -i /bladerf/d $SIGPI_INSTALLED_DEVICES
        
	    cd $SIGPI_SOURCE/SoapyBladeRF/build
        sudo make uninstall
        sudo ldconfig
        cd $SIGPI_SOURCE
        rm -rf $SIGPI_SOURCE/SoapyBladeRF
        rm -rf $HOME/.config/bladerf
        sudo rm -rf $SIGPI_DESKTOP/bladerf.desktop
        sudo rm -rf $DESKTOP_FILES/bladerf.desktop
        sed -i /SoapyBladeRF/d $SIGPI_INSTALLED_DEVICES
        ;;&

    install|build|package )
        ## DEPENDENCIES
        sudo apt-get install -y python3-six python3-mako python3-lxml 
        sudo apt-get install -y python3-numpy python3-numpy python3-pip python3-pybind11 libsndfile1-dev
        ;;&

    install )
        ## REPO
        sudo add-apt-repository -y ppa:nuandllc/bladerf
        sudo apt update

        ## PACKAGE
        sudo apt-get install -y bladerf libbladerf-dev
        cat $SIGPI_DEVLIST|grep "bladerf" >> $SIGPI_INSTALLED_DEVICES

        ### SoapyBladeRF
        cd $SIGPI_SOURCE
        git clone https://github.com/pothosware/SoapyBladeRF.git
        cd SoapyBladeRF
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        sudo ldconfig
        ;;&

    build )
        ## DEPENDENCIES
        sudo apt-get install -y python3-six python3-mako python3-lxml python3-numpy 
        sudo apt-get install -y python3-pip git python3-pybind11 libsndfile1-dev
        ## PACKAGE 
        
        ### BladeRF
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch 2025.10 https://github.com/Nuand/bladeRF.git
        cd bladeRF/host
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        sudo ldconfig
        cat $SIGPI_DEVLIST|grep "bladerf" >> $SIGPI_INSTALLED_DEVICES

        ### SoapyBladeRF
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch soapy-bladerf-0.4.2 https://github.com/pothosware/SoapyBladeRF.git
        cd SoapyBladeRF
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        sudo make install
        ;;&

    package )
        ## PACKAGE

        ### BladeRF
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch 2025.10 https://github.com/Nuand/bladeRF.git
        cd bladeRF/host
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "bladerf" "2025.10" "$(pwd)/pkgroot" "Nuand bladeRF host tools and libraries"
        rm -rf pkgroot

        ### SoapyBladeRF
        cd $SIGPI_SOURCE
        git clone --depth 1 --branch soapy-bladerf-0.4.2 https://github.com/pothosware/SoapyBladeRF.git
        cd SoapyBladeRF
        mkdir build && cd build
        cmake .. -Wno-dev
        make -j4
        rm -rf pkgroot && mkdir -p pkgroot
        make DESTDIR="$(pwd)/pkgroot" install
        sigpi_stage_package "soapybladerf" "0.4.2" "$(pwd)/pkgroot" "SoapySDR module for Nuand bladeRF devices"
        rm -rf pkgroot
        ;;&

    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : BladeRF - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac
