#!/bin/bash

###
### SIGPI
###
### pkg_cubicsdr
###
###
### 20260112-2300
###

if [[ ! "$1" =~ ^(remove|purge|install|build|package)$ ]]; then
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unknown action or package"
    echo -e "${SIGPI_BANNER_RESET}"
    exit 1
fi

case "$1" in
    remove|purge|install|build|package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : CubicSDR"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;&

    remove )
        sudo apt-get remove cubicsdr
        sed -i /cubicsdr/d $SIGPI_INSTALLED
        ;;&

    purge )
        sudo apt-get remove --purge cubicsdr
        sed -i /cubicsdr/d $SIGPI_INSTALLED
        ;;&

    install)
        ## DEPENDENCIES
        sudo apt-get install -y libpulse-dev libgtk-3-dev
        sudo apt-get install -y freeglut3 freeglut3-dev

        ## PACKAGE
        cd $SIGPI_SOURCE
        sudo apt-get install -y cubicsdr  # v0.2.5
        cat $SIGPI_PKGLIST|grep "cubicsdr" >> $SIGPI_INSTALLED 
	
	    ## DESKTOP
        # Add Icon
        # Add Desktop
        # Add Category
        sudo sed -i "s/Categories.*/Categories=$SIGPI_MENU_CATEGORY;/" $DESKTOP_FILES/CubicSDR.desktop
        # Add to Menu
        xdg-desktop-menu install --novendor --noupdate $DESKTOP_DIRECTORY/SIGpi.directory $DESKTOP_FILES/CubicSDR.desktop
        ;;&

    build )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Build option not available"
        echo -e "${SIGPI_BANNER_RESET}"
	    ;;&

    package )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Package option not available"
        echo -e "${SIGPI_BANNER_RESET}"
	    ;;&

    remove|purge|install )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  $1 : CubicSDR - Completed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac

