#!/bin/bash

###
### SIGPI
###
### pkg_linpac
###

case "$1" in 
    remove )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Remove Linpac"
        echo -e "${SIGPI_BANNER_RESET}"

        sudo apt-get remove linpac

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Linpac Removed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    purge )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Purge linpac"
        echo -e "${SIGPI_BANNER_RESET}"

        sudo apt-get remove --purge linpac
        
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Linpac Purged"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    install )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##   Install Linpac"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"

        ## DEPENDENCIES

        ## PACKAGE
        cd $SIGPI_SOURCE
        sudo apt-get install -y linpac

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##   Linpac Installed"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
    * )
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: Unkown action or package"
        echo -e "${SIGPI_BANNER_RESET}"
        ;;
esac