#!/bin/bash

###
### SIGPI
###
### setup_devices
###
###
### 20260117-2300
###
### Devices installed by default include RTLSDR, HackRF, and Ubertooth
### Related software includes SoapySDR, SoapyRemote, SoapyRTLSDR, SoapyHackRF, and GPS
###


echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##"
echo -e "${SIGPI_BANNER_COLOR} ##  Setup Devices"
echo -e "${SIGPI_BANNER_COLOR} ##"
echo -e "${SIGPI_BANNER_RESET}"

# SoapySDR 0.8
echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##  install : SoapySDR "
echo -e "${SIGPI_BANNER_RESET}"

sudo apt-get install -y libusb-1.0-0-dev soapysdr-tools libsoapysdr-dev

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##  install : SoapySDR - Completed"
echo -e "${SIGPI_BANNER_RESET}"

# SoapyRemote
echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##  install : SoapyRemote "
echo -e "${SIGPI_BANNER_RESET}"

sudo apt-get install -y soapyremote-server soapysdr-module-remote

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##  install : SoapyRemote - Completed"
echo -e "${SIGPI_BANNER_RESET}"

# Install AX.25
#source $SIGPI_PACKAGES/pkg_ax25 install

# Install bladeRF
if grep bladerf "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_bladerf install
fi

# Install Ettus UHD
if grep ettus "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_ettus install
fi

# Install RigExpert Fobos
if grep fobos "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_libfobos install
fi

# Install HackRf
source $SIGPI_DEVICES/pkg_hackrf install

# Install KerberosSDR
if grep kerberos "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_rtl-sdr-kerberos install
fi

# Install LimeSDR
if grep limesuite "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_limesuite install
fi

# Install PlutoSDR
if grep plutosdr "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_plutosdr install
fi

# Install RTLSDR
source $SIGPI_DEVICES/pkg_rtlsdr-v4 install

# Install SDRPlay
if grep sdrplay "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_sdrplay install
fi

# Install Ubertooth One
if grep ubertooth "$SIGPI_INSTALLED_DEVICES"; then
    source $SIGPI_DEVICES/pkg_ubertooth install
fi

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##"
echo -e "${SIGPI_BANNER_COLOR} ##  Setup Devices: Complete"
echo -e "${SIGPI_BANNER_COLOR} ##"
echo -e "${SIGPI_BANNER_RESET}"