#!/bin/bash

###
### SIGpi
###
### SIGpi_setup
###

###
###  REVISION: 20260110-2300
###

###
###  Usage:    SIGpi_setup
###
###            Fresh install of SIGpi on a fresh OS install
###
###
###

###
### Environment tests
### 

# Are we the right hardware
if [ "$SIGPI_HWARCH" = "x86_64" ] || [ "$SIGPI_HWARCH" = "aarch64" ]; then
    SIGPI_CERTIFIED="true"
fi

# Are we the right operating system
SIGPI_OSCODENAME=`cat /etc/os-release|grep "VERSION_CODENAME"|awk -F'=' '{print $2}'`
if [ "$SIGPI_OSCODENAME" = "noble" ]; then
    SIGPI_CERTIFIED="true"
fi
if [ "$SIGPI_CERTIFIED" = "false" ]; then
    echo "ERROR:"
    echo "ERROR:  Incorrect Hardware or Operating System"
    echo "ERROR:"
    echo "ERROR:  Hardware must be x86_64 or aarch64 hardware - Aborting"
    echo "ERROR:  Operating system must be noble (Ubuntu 24.04 LTS) - Aborting"
    echo "ERROR:"
    exit 1;
fi


###
### FUNCTIONS
###

calc_wt_size() {
  # NOTE: it's tempting to redirect stderr to /dev/null, so supress error 
  # output from tput. However in this case, tput detects neither stdout or 
  # stderr is a tty and so only gives default 80, 24 values
  WT_HEIGHT=26
  WT_WIDTH=$(tput cols)

  if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
    WT_WIDTH=60
  fi
  if [ "$WT_WIDTH" -gt 178 ]; then
    WT_WIDTH=80
  fi
  WT_MENU_HEIGHT=$(($WT_HEIGHT-7))
}

select_startscreen(){
    TERM=ansi whiptail --title "SIGpi Setup" --clear --textbox $SIGPI_SCREEN_STANDARD 34 100 16
}

select_startsrvscreen(){
    TERM=ansi whiptail --title "SIGpi Server Setup" --clear --textbox $SIGPI_SCREEN_SERVER 34 100 16
}

select_devices() {
    FUN=$(whiptail --title "Devices Setup" --clear --checklist --separate-output \
        "Choose SDR devices " 20 80 12 \
        "bladerf" "bladeRF " OFF \
        "ettus" "Ettus Research USRP UHD " OFF \
        "fobos" "RigExpert Fobos " OFF\
        "hackrf" "HackRF v1" ON\
        "kerberos" "Kerberos SDR " OFF\
        "limesuite" "LimeSDR " OFF \
        "plutosdr" "PlutoSDR " OFF \
        "rtlsdr-v4" "RTLSDR v4 " ON\
        "sdrplay" "SDRPlay " OFF \
        "ubertooth" "Ubertooth One" OFF \
        3>&1 1>&2 2>&3)
    RET=$?
    if [ $RET -eq 1 ]; then
        $FUN = "NONE"
    fi

    IFS=' '     # space is set as delimiter
    read -ra ADDR <<< "$FUN"   # str is read into an array as tokens separated by IFS
    for i in "${ADDR[@]}"; do   # access each element of array
        echo $FUN >> $SIGPI_INSTALLED_DEVICES
    done
}

select_server() {
    FUN=$(whiptail --title "Server Setup" --clear --checklist --separate-output \
        "Choose which server to run as a service" 20 120 12 \
        "openwebrx" "OpenWebRX " OFF \
        "rtltcpsrv" "RTL-TCP Server " OFF \
        "sdrangelsrv" "SDRangel Server " OFF \
        "soapysdrsrv" "SoapySDR Server " OFF \
        "radiosonde" "RadioSonde AutoRX " OFF \
		3>&1 1>&2 2>&3)
    RET=$?
    if [ $RET -eq 1 ]; then
        $FUN = "NONE"
    fi

    IFS=' '     # space is set as delimiter
    read -ra ADDR <<< "$FUN"   # str is read into an array as tokens separated by IFS
    for i in "${ADDR[@]}"; do   # access each element of array
        echo $FUN >> $SIGPI_INSTALLED_DEVICES
    done
}

system_current() {
    echo -e "${SIGPI_BANNER_COLOR}"
    echo -e "${SIGPI_BANNER_COLOR} ##"
    echo -e "${SIGPI_BANNER_COLOR} ##  System Update & Upgrade"
    echo -e "${SIGPI_BANNER_COLOR} ##"
    echo -e "${SIGPI_BANNER_RESET}"

    sudo apt-get -y update
    sudo apt-get -y upgrade
}


###
###  MAIN
###

# Setup directories
mkdir $SIGPI_ETC
touch $SIGPI_INSTALLED
mkdir $SIGPI_SOURCE
cd $SIGPI_SOURCE


##
## Server Install 
##

case "$1" in
    server )
        calc_wt_size
        select_startsrvscreen
        select_devices
        select_server
        TERM=ansi whiptail --title "SIGpi Server Setup" --clear --msgbox "Ready to continue" 12 120
        system_current

        cd $SIGPI_SOURCE

        source $SIGPI_SCRIPTS/setup_core_server
        source $SIGPI_SCRIPTS/setup_devices
        source $SIGPI_SCRIPTS/setup_core_packages

        # Copy SIGpi commands into /usr/local/bin
        sudo cp $SIGPI_HOME/scripts/SIGpi_exec-in-shell /usr/local/bin/SIGpi_exec-in-shell 
        sudo cp $SIGPI_HOME/SIGpi /usr/local/bin/SIGpi
  
       # Install RTL-TCP Server
        if grep -q "rtltcpsrv" "$SIGPI_INSTALLED_DEVICES"; then
            sudo cp $SIGPI_CONFIG/rtltcp.service /etc/systemd/system/sigpi-node.service
            echo "sigpi-node_rtltcp" >> $SIGPI_INSTALLED
        fi
       # Install SDRangel Server
        if grep -q "sdrangelsrv" "$SIGPI_INSTALLED_DEVICES"; then
            source $SIGPI_PACKAGES/pkg_sdrangelsrv install
            sudo cp $SIGPI_CONFIG/sdrangelsrv.service /etc/systemd/system/sigpi-node.service
            echo "sigpi-node_sdrangelsrv" >> $SIGPI_INSTALLED
        fi
        # Install SoapySDR Server
        if grep -q "soapysdrsrv" "$SIGPI_INSTALLED_DEVICES"; then
            sudo cp $SIGPI_CONFIG/soapysdrsrv.service /etc/systemd/system/sigpi-node.service
            echo "sigpi-node_soapysdrsrv" >> $SIGPI_INSTALLED
        fi
        # Install OpenWebRX
        if grep -q "openwebrx" "$SIGPI_INSTALLED_DEVICES"; then
            source $SIGPI_PACKAGES/pkg_openwebrx install
            sudo cp $SIGPI_CONFIG/openwebrx.service /etc/systemd/system/openwebrx.service
            echo "sigpi-node_openwebrx" >> $SIGPI_INSTALLED
        fi
        # Install RadioSonde AutoRX
        if grep -q "radiosonde" "$SIGPI_INSTALLED_DEVICES"; then
            source $SIGPI_PACKAGES/pkg_radiosonde_autorx install
            echo "sigpi-node_radiosonde_autorx" >> $SIGPI_INSTALLED
        fi
        
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##  Server Setup Complete !!"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##  System needs to reboot for all changes to occur"
        echo -e "${SIGPI_BANNER_COLOR} ##  Reboot will begin in 15 seconsds unless CTRL-C hit"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"
        sleep 15
        sudo sync
        sudo reboot
        exit 0
        ;;
    framework )
        calc_wt_size
        select_startscreen
        select_devices
        TERM=ansi whiptail --title "SIGpi setup" --clear --msgbox "Ready to continue" 12 120
        system_current

        cd $SIGPI_SOURCE
        source $SIGPI_SCRIPTS/setup_core_standard
        source $SIGPI_SCRIPTS/setup_devices
        
        # Copy SIGpi commands into /usr/local/bin
        sudo cp $SIGPI_HOME/scripts/SIGpi_exec-in-shell /usr/local/bin/SIGpi_exec-in-shell 
        sudo cp $SIGPI_HOME/SIGpi /usr/local/bin/SIGpi

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##  Framework Setup Complete !!"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##  System needs to reboot for all changes to occur"
        echo -e "${SIGPI_BANNER_COLOR} ##  Reboot will begin in 15 seconsds unless CTRL-C hit"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"
        sleep 15
        sudo sync
        sudo reboot
        exit 0
        ;;
    standard )
        calc_wt_size
        select_startscreen
        select_devices
        TERM=ansi whiptail --title "SIGpi setup" --clear --msgbox "Ready to continue" 12 120
        system_current

        cd $SIGPI_SOURCE

        source $SIGPI_SCRIPTS/setup_core_standard
        source $SIGPI_SCRIPTS/setup_devices
        source $SIGPI_SCRIPTS/setup_core_packages
        source $SIGPI_SCRIPTS/setup_core_desktop

        # Copy SIGpi commands into /usr/local/bin
        sudo cp $SIGPI_SCRIPTS/SIGpi_exec-in-shell /usr/local/bin/SIGpi_exec-in-shell 
        sudo cp $SIGPI_HOME/SIGpi /usr/local/bin/SIGpi

        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##  Standard Setup Complete !!"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR}"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##  System needs to reboot for all changes to occur"
        echo -e "${SIGPI_BANNER_COLOR} ##  Reboot will begin in 15 seconsds unless CTRL-C hit"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_RESET}"
        sleep 15
        sudo sync
        sudo reboot
        exit 0
        ;;
    * )
        echo -e "${SIGPI_BANNER_COLOR} ##"
        echo -e "${SIGPI_BANNER_COLOR} ##  ERROR: SIGpi setup <TARGET>"
        echo -e "${SIGPI_BANNER_COLOR} ##"
        ;;
esac