#!/usr/bin/env sh

###
### SIGpi
###
### SIGpi_exec-in-shell
###

###
###  REVISION: 20260110-2300
###

echo "$ $@"
eval $@

USER=${USER:-$(whoami)}
SHELL=${SHELL:-$(getent passwd $USER | cut -d: -f7)}
${SHELL:-bash} -i